### ISSUE TITLE
I can't use calamity accessories in this mod...

### ISSUE THREAD

**Issue by elmaxitos** [Chicken-Bones/UtilitySlots#1]
Hello, I just downloaded your mod from this github link (https://github.com/Chicken-Bones/UtilitySlots#readme), and wanting to equip the "Seraph Tracers" accessory of "Calamity mod" does not let me, I tried adding them with the mod files but I couldn't, and I wanted to know if you could add them to this mod.
Have a good day

Edit; I already solved it, the reason why it did not work for me was because the mod "Wing Slot" has an option called "Allow equipping in accesory slots" and I had it disabled, when I activated it I could use the boots of calamity with the mod utility slots :D

**Comment by MaxiElegancia** [comment]
> Hello, I just downloaded your mod from this github link (https://github.com/Chicken-Bones/UtilitySlots#readme), and wanting to equip the "Seraph Tracers" accessory of "Calamity mod" does not let me, I tried adding them with the mod files but I couldn't, and I wanted to know if you could add them to this mod.
> Have a good day

**Comment by Chicken-Bones** [comment]
Wait you wrote a compatibility mod!? Tell me more! Come PM me on Discord
